spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: simple-bills
      uri: mongodb+srv://simple:bills@cluster0.i30j4gd.mongodb.net/?retryWrites=true&w=majority
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/baeldung
          jwk-set-uri: http://localhost:8085/realms/baeldung/protocol/openid-connect/certs

server:
  error:
    include-stacktrace: never

simpleBillsGuiAppUrl: "http://localhost:8089"