spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: transaction
      uri: mongodb+srv://simple:bills@cluster0.i30j4gd.mongodb.net/?retryWrites=true&w=majority
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://37.233.102.95:8443/realms/simple-bills
          jwk-set-uri: https://37.233.102.95:8443/realms/simple-bills/protocol/openid-connect/certs

server:
  error:
    include-stacktrace: never

simpleBillsGuiAppUrl: "https://simple-bills-lukaszse.cloud.okteto.net/"