spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    mongodb:
      database: simple-bills
      uri: mongodb+srv://simple:bills@cluster0.i30j4gd.mongodb.net/?retryWrites=true&w=majority

server:
  error:
    include-stacktrace: never

#custom
hello: "Hello %s, Welcome in my application!"