spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    mongodb:
      database: simple-bills
      uri: mongodb://mongodb:27017

server:
  error:
    include-stacktrace: never

simpleBillsGuiAppUrl: "http://localhost:8089"